### ISSUE TITLE
[FEAT] Using linter

### ISSUE THREAD

**Issue by mimani68** [GoFarsi/clean-layout#1]
I conjecture linters file and manifest would enrich this repo as well 

> [golangci-lint.run/](https://golangci-lint.run/usage/configuration)

like

```yaml
# Options for analysis running.
run:
  # See the dedicated "run" documentation section.
  option: value
# output configuration options
output:
  # See the dedicated "output" documentation section.
  option: value
# All available settings of specific linters.
linters-settings:
  # See the dedicated "linters-settings" documentation section.
  option: value
linters:
  # See the dedicated "linters" documentation section.
  option: value
issues:
  # See the dedicated "issues" documentation section.
  option: value
severity:
  # See the dedicated "severity" documentation section.
  option: value
```
